services:
  postgres-inventory:
    image: postgres:17
    container_name: postgres-inventory
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secretpassword}
      POSTGRES_DB: ${POSTGRES_DB:-inventory}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres_inventory_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-inventory}"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  postgres-orders:
    image: postgres:17
    container_name: postgres-orders
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secretpassword}
      POSTGRES_DB: ${POSTGRES_DB:-orders}
    ports:
      - "6543:5432"
    volumes:
      - ./data/postgres_orders_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-orders}"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  victorialogs:
    image: victoriametrics/victoria-logs:v1.18.0-victorialogs
    container_name: victorialogs
    ports:
      - "9428:9428"
    volumes:
      - ./data/victorialogs-data:/victoria-logs-data
    command:
      - "--storageDataPath=/victoria-logs-data"
      - "--httpListenAddr=:9428"
    restart: unless-stopped
