services:
  postgres-inventory:
    image: postgres:17
    container_name: fungicibus-postgres-inventory
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secretpassword}
      POSTGRES_DB: ${POSTGRES_DB:-inventory}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres-inventory-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-inventory}"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  postgres-orders:
    image: postgres:17
    container_name: fungicibus-postgres-orders
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secretpassword}
      POSTGRES_DB: ${POSTGRES_DB:-orders}
    ports:
      - "6543:5432"
    volumes:
      - ./data/postgres-orders-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-orders}"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  victorialogs:
    image: victoriametrics/victoria-logs:v1.18.0-victorialogs
    container_name: fungicibus-victorialogs
    ports:
      - "9428:9428"
    volumes:
      - ./data/victorialogs-data:/victoria-logs-data
    command:
      - "--storageDataPath=/victoria-logs-data"
      - "--httpListenAddr=:9428"
    restart: unless-stopped

  kafka:
    image: apache/kafka:4.0.0
    container_name: fungicibus-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_DIRS: /opt/kafka/data
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    volumes:
      - ./data/kafka-data:/opt/kafka/data
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9092"]
      interval: 30s
      timeout: 10s
      retries: 3

  redpanda-console:
    image: redpandadata/console:latest
    container_name: fungicibus-redpanda-console
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./data/redpanda-console-data:/tmp/redpanda-console 
    environment:
      KAFKA_BROKERS: kafka:29092
      REDPANDA_CONSOLE_CONFIG: |
        kafka:
          brokers: ["kafka:9092"]
          schemaRegistry:
            enabled: false
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3